import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        "on-secondary-fixed": "var(--on-secondary)",
        "error": "rgb(var(--error-rgb) / <alpha-value>)",
        "tertiary-container": "var(--tertiary-container)",
        "error-container": "var(--error-container)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "secondary-container": "var(--secondary-container)",
        "on-tertiary-container": "var(--on-primary-container)",
        "surface-dim": "var(--surface-dim)",
        "surface-variant": "rgb(var(--surface-variant-rgb) / <alpha-value>)",
        "surface-container": "var(--surface-container)",
        "on-secondary": "var(--on-secondary)",
        "on-tertiary-fixed": "var(--text-primary)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary": "var(--tertiary)",
        "on-surface-variant": "rgb(var(--text-secondary-rgb) / <alpha-value>)",
        "on-tertiary-fixed-variant": "var(--text-secondary)",
        "on-primary-fixed-variant": "var(--text-secondary)",
        "surface": "rgb(var(--bg-surface-rgb) / <alpha-value>)",
        "inverse-primary": "var(--primary)",
        "on-error": "var(--text-primary)",
        "primary": "rgb(var(--primary-rgb) / <alpha-value>)",
        "outline": "rgb(var(--outline-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--text-primary-rgb) / <alpha-value>)",
        "on-primary-fixed": "var(--on-primary)",
        "on-secondary-fixed-variant": "var(--text-secondary)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary": "var(--on-primary)",
        "primary-fixed": "var(--primary)",
        "secondary-fixed": "var(--secondary)",
        "on-error-container": "var(--text-primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-container-high": "rgb(var(--surface-container-high-rgb) / <alpha-value>)",
        "primary-fixed-dim": "var(--primary)",
        "surface-bright": "var(--surface-bright)",
        "inverse-surface": "var(--bg-surface)",
        "tertiary-fixed": "var(--tertiary)",
        "secondary": "rgb(var(--secondary-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "surface-tint": "var(--primary)",
        "on-secondary-container": "var(--on-secondary)",
        "on-background": "rgb(var(--text-primary-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "var(--tertiary)",

        background: "rgb(var(--bg-surface-rgb) / <alpha-value>)",
        foreground: "rgb(var(--text-primary-rgb) / <alpha-value>)",
        card: {
          DEFAULT: "rgb(var(--bg-surface-rgb) / <alpha-value>)",
          foreground: "rgb(var(--text-primary-rgb) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "rgb(var(--bg-surface-rgb) / <alpha-value>)",
          foreground: "rgb(var(--text-primary-rgb) / <alpha-value>)",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        header_height: "36px",
        container_padding: "20px",
        sidebar_width: "260px",
        gutter: "16px",
        footer_height: "32px",
      },
      fontFamily: {
        "terminal-mono": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        "headline-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-base": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "status-chip": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        "headline-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-sm": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
      },
      fontSize: {
        "terminal-mono": ["14px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "status-chip": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      backdropBlur: {
        xs: "2px",
        glass: "18px",
        "glass-heavy": "40px",
      },
      keyframes: {
        "dialog-in": {
          from: { opacity: "0", transform: "scale(0.95) translateY(12px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "drop-in": {
          from: { opacity: "0", transform: "translateY(-6px) scale(0.97)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(12px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "modal-in": {
          from: { opacity: "0", transform: "translateY(20px) scale(0.95)", filter: "blur(10px)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)", filter: "blur(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.35" },
        },
      },
      animation: {
        "dialog-in": "dialog-in var(--duration-slow) var(--ease-out)",
        "drop-in": "drop-in var(--duration-slow) var(--ease-spring)",
        "slide-in-right": "slide-in-right var(--duration-base) var(--ease-out)",
        "slide-up": "slide-up var(--duration-base) var(--ease-out)",
        "fade-in": "fade-in var(--duration-base) var(--ease-default)",
        "scale-in": "scale-in var(--duration-slow) var(--ease-spring)",
        "modal-in": "modal-in 0.3s var(--ease-out)",
        pulse: "pulse 1.5s infinite",
      },
    },
  },
  plugins: [animate],
} satisfies Config;