import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        "on-secondary-fixed": "#00210c",
        "error": "#ffb4ab",
        "tertiary-container": "#9d8eff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#00b55d",
        "on-tertiary-container": "#3109a3",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "surface-container": "#201f1f",
        "on-secondary": "#003919",
        "on-tertiary-fixed": "#190064",
        "on-tertiary": "#2d009d",
        "tertiary": "#c8bfff",
        "on-surface-variant": "#c5c6cf",
        "on-tertiary-fixed-variant": "#442bb5",
        "on-primary-fixed-variant": "#354768",
        "surface": "#131313",
        "inverse-primary": "#4d5e81",
        "on-error": "#690005",
        "primary": "#b5c7ef",
        "outline": "#8e9098",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#061b3a",
        "on-secondary-fixed-variant": "#005227",
        "on-primary-container": "#223454",
        "on-primary": "#1e3050",
        "primary-fixed": "#d7e2ff",
        "secondary-fixed": "#6dfe9c",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#b5c7ef",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#e5deff",
        "secondary": "#4de082",
        "outline-variant": "#44474e",
        "surface-tint": "#b5c7ef",
        "on-secondary-container": "#003e1c",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed-dim": "#c8bfff",
        "secondary-fixed-dim": "#4de082",
        "inverse-on-surface": "#313030",
        "primary-container": "#8b9dc3",
        "background": "#131313",
        
        background: "#131313",
        foreground: "#e5e2e1",
        card: {
          DEFAULT: "#131313",
          foreground: "#e5e2e1",
        },
        popover: {
          DEFAULT: "#1a1a1a",
          foreground: "#e5e2e1",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        header_height: "36px",
        container_padding: "20px",
        sidebar_width: "260px",
        gutter: "16px",
        footer_height: "32px",
      },
      fontFamily: {
        "terminal-mono": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        "headline-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-base": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "status-chip": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        "headline-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-sm": ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Cascadia Code", "Consolas", "monospace"],
      },
      fontSize: {
        "terminal-mono": ["14px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "status-chip": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      backdropBlur: {
        xs: "2px",
        glass: "18px",
        "glass-heavy": "40px",
      },
      keyframes: {
        "dialog-in": {
          from: { opacity: "0", transform: "scale(0.95) translateY(12px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "drop-in": {
          from: { opacity: "0", transform: "translateY(-6px) scale(0.97)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(12px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "modal-in": {
          from: { opacity: "0", transform: "translateY(20px) scale(0.95)", filter: "blur(10px)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)", filter: "blur(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.35" },
        },
      },
      animation: {
        "dialog-in": "dialog-in var(--duration-slow) var(--ease-out)",
        "drop-in": "drop-in var(--duration-slow) var(--ease-spring)",
        "slide-in-right": "slide-in-right var(--duration-base) var(--ease-out)",
        "slide-up": "slide-up var(--duration-base) var(--ease-out)",
        "fade-in": "fade-in var(--duration-base) var(--ease-default)",
        "scale-in": "scale-in var(--duration-slow) var(--ease-spring)",
        "modal-in": "modal-in 0.3s var(--ease-out)",
        pulse: "pulse 1.5s infinite",
      },
    },
  },
  plugins: [animate],
} satisfies Config;